# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true

# These are versioned per target; see versions/<mc>/gradle.properties
minecraft_version=[VERSIONED]
loader_version=[VERSIONED]
fabric_version=[VERSIONED]
malilib_version=[VERSIONED]
java_version=[VERSIONED]

# Mod Properties
mod_version=0.1.2
maven_group=net.villagercensus
archives_base_name=villagercensus
